[project]
name = "wmsdump"
version = "0.1.0"
description = "Library for extraction of data from WMS/WFS endpoints"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "click>=8.1.7",
    "jsonschema>=4.23.0",
    "lxml>=5.3.0",
    "requests>=2.32.3",
    "xmltodict>=0.14.2",
]

[project.scripts]
wms-extracter = "wmsdump.cli:main"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
